### Data Extraction from Yahoo Finance website
- Link: https://finance.yahoo.com/quote/BTC-USD/

In [1]:
# Imports 
import yfinance as yf
import pandas as pd
import os

In [2]:
# Create Bitcoin ticker
ticker_bitcoin = "BTC-USD"

Note: A ticker is a symbol, a unique combination of letters and numbers that represents a particular stock or security listed on an exchange

In [3]:
# Create a Ticker object
bitcoin = yf.Ticker(ticker_bitcoin)

#### Params to download historical data
1. Method: .history()
2. Params:
    - period: "1d", "1mo", "1y", "ytd", "max".
    - interval: "1m", "1h", "1d", "1wk", "1mo".
    - start: "YYYY-MM-DD".
    - end: "YYYY-MM-DD".

#### Download max historical data by 1-day interval:

In [4]:
# Extract all the historical price data 
historical_data_max_daily_df = bitcoin.history(period="max", interval="1d")
historical_data_max_daily_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3950 entries, 2014-09-17 00:00:00+00:00 to 2025-07-11 00:00:00+00:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          3950 non-null   float64
 1   High          3950 non-null   float64
 2   Low           3950 non-null   float64
 3   Close         3950 non-null   float64
 4   Volume        3950 non-null   int64
 5   Dividends     3950 non-null   float64
 6   Stock Splits  3950 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 246.9 KB

In [5]:
# Use the .describe() method to get quick statistical insight from the data
historical_data_max_daily_df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,3950.000000,3950.000000,3950.000000,3950.000000,3.950000e+03,3950.0,3950.0
mean,23290.523212,23788.552618,22770.134340,23317.647888,1.982783e+10,0.0,0.0
std,27247.499191,27774.615840,26700.395909,27280.521777,2.106932e+10,0.0,0.0
min,176.897003,211.731003,171.509995,178.102997,5.914570e+06,0.0,0.0
25%,2238.980042,2331.427551,2150.370056,2260.065063,9.384445e+08,0.0,0.0
50%,10031.268555,10233.897949,9724.194824,10055.251953,1.599609e+10,0.0,0.0
75%,37445.751953,38536.031250,36393.588867,37475.740234,3.124460e+10,0.0,0.0
max,115984.171875,116762.062500,115305.195312,116745.945312,3.509679e+11,0.0,0.0

In [6]:
# Show the Dataframe
historical_data_max_daily_df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,0.0,0.0
2014-09-18 00:00:00+00:00,456.859985,456.859985,413.104004,424.440002,34483200,0.0,0.0
2014-09-19 00:00:00+00:00,424.102997,427.834991,384.532013,394.795990,37919700,0.0,0.0
2014-09-20 00:00:00+00:00,394.673004,423.295990,389.882996,408.903992,36863600,0.0,0.0
2014-09-21 00:00:00+00:00,408.084991,412.425995,393.181000,398.821014,26580100,0.0,0.0

### Save the data in the data folder

In [7]:
# Create a variable that holds the file name
file_name = "bitcoin_historical_price_daily.csv"

# Create the alternative route to the "data" folder
route_folder = os.path.join("..", "data", "raw", file_name)

# Save the DataFrame in the specified route folder
historical_data_max_daily_df.to_csv(route_folder, index=True)

print(f"The file '{file_name}' was saved successfully in: {route_folder}")

The file 'bitcoin_historical_price_daily.csv' was saved successfully in: ..\data\raw\bitcoin_historical_price_daily.csv

In [8]:
historical_data_max_daily_df.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-07-06 00:00:00+00:00,108231.187500,109731.62500,107847.015625,109232.070312,36746020463,0.0,0.0
2025-07-07 00:00:00+00:00,109235.328125,109710.25000,107527.054688,108299.851562,45415696597,0.0,0.0
2025-07-08 00:00:00+00:00,108298.226562,109198.96875,107499.554688,108950.273438,44282204127,0.0,0.0
2025-07-09 00:00:00+00:00,108950.273438,111925.37500,108357.679688,111326.554688,57927418065,0.0,0.0
2025-07-11 00:00:00+00:00,115984.171875,116762.06250,115305.195312,116745.945312,100835975168,0.0,0.0