### Data Extraction from Yahoo Finance website
- Link: https://finance.yahoo.com/quote/BTC-USD/

In [8]:
# Imports 
import yfinance as yf
import pandas as pd
import os

In [9]:
# Create Bitcoin ticker
ticker_bitcoin = "BTC-USD"

Note: A ticker is a symbol, a unique combination of letters and numbers that represents a particular stock or security listed on an exchange

In [10]:
# Create a Ticker object
bitcoin = yf.Ticker(ticker_bitcoin)

#### Params to download historical data
1. Method: .history()
2. Params:
    - period: "1d", "1mo", "1y", "ytd", "max".
    - interval: "1m", "1h", "1d", "1wk", "1mo".
    - start: "YYYY-MM-DD".
    - end: "YYYY-MM-DD".

#### Download max historical data by 1-day interval:

In [11]:
# Extract all the historical price data 
historical_data_max_daily_df = bitcoin.history(period="max", interval="1d")
historical_data_max_daily_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3948 entries, 2014-09-17 00:00:00+00:00 to 2025-07-08 00:00:00+00:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          3948 non-null   float64
 1   High          3948 non-null   float64
 2   Low           3948 non-null   float64
 3   Close         3948 non-null   float64
 4   Volume        3948 non-null   int64
 5   Dividends     3948 non-null   float64
 6   Stock Splits  3948 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 246.8 KB

In [12]:
# Use the .describe() method to get quick statistical insight from the data
historical_data_max_daily_df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,3948.000000,3948.000000,3948.000000,3948.000000,3.948000e+03,3948.0,3948.0
mean,23245.343060,23742.671292,22725.039220,23271.680717,1.979737e+10,0.0,0.0
std,27180.207828,27706.653964,26631.724744,27210.773058,2.102608e+10,0.0,0.0
min,176.897003,211.731003,171.509995,178.102997,5.914570e+06,0.0,0.0
25%,2232.670044,2318.385071,2140.320068,2250.042603,9.364403e+08,0.0,0.0
50%,9987.777832,10224.472168,9720.184570,10035.710449,1.597491e+10,0.0,0.0
75%,37397.245117,38408.531250,36375.064453,37442.277344,3.121404e+10,0.0,0.0
max,111679.359375,111970.171875,109285.070312,111673.281250,3.509679e+11,0.0,0.0

In [13]:
# Show the Dataframe
historical_data_max_daily_df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,0.0,0.0
2014-09-18 00:00:00+00:00,456.859985,456.859985,413.104004,424.440002,34483200,0.0,0.0
2014-09-19 00:00:00+00:00,424.102997,427.834991,384.532013,394.795990,37919700,0.0,0.0
2014-09-20 00:00:00+00:00,394.673004,423.295990,389.882996,408.903992,36863600,0.0,0.0
2014-09-21 00:00:00+00:00,408.084991,412.425995,393.181000,398.821014,26580100,0.0,0.0

### Save the data in the data folder

In [14]:
# Create a variable that holds the file name
file_name = "bitcoin_historical_price_daily.csv"

# Create the alternative route to the "data" folder
route_folder = os.path.join("..", "data", "raw", file_name)

# Save the DataFrame in the specified route folder
historical_data_max_daily_df.to_csv(route_folder, index=True)

print(f"The file '{file_name}' was saved successfully in: {route_folder}")

The file 'bitcoin_historical_price_daily.csv' was saved successfully in: ..\data\raw\bitcoin_historical_price_daily.csv